config/routes.rb
Rails.application.routes.draw do

  root 'restaurants#index'

  resources :sessions, only: [:new, :create, :destroy]

  resources :users do
    resources :reservations, only: [:destroy, :show]
  end

  resources :restaurants do
    resources :reservations, only: [:new, :create, :destroy, :show]
    resources :tables
  end

  resources :reservations do
    resources :restaurants, only: [:show]
    resources :users, only: [:show]
  end

end

app/models/reservation.rb
class Reservation < ActiveRecord::Base
	belongs_to :user
  belongs_to :restaurant
	has_many :tables, through: :restaurant

  validates :party_size, presence: true, numericality: {only_integer: true}
end

app/models/restaurant.rb
class Restaurant < ActiveRecord::Base

	belongs_to :owner, class_name: 'User', foreign_key: 'user_id'

	has_many :tables
	has_many :reservations
	has_many :users, through: :reservations

	validates :name, presence: true


	def is_available?(party_size, time)
		self.get_current_capacity(time) >= party_size
	end

	def get_current_capacity(time)
		available_tables(time).sum(:capacity)
	end

	def find_tables_for_party(party_size, time)
		(1..available_tables(time).length).each do |i|
			available_tables(time).combination(i).to_a.each do |combination|
				combination_capacity = 0
				combination.each do |table|
					combination_capacity += table.capacity
				end
				if combination_capacity >= party_size
					return combination
				end
			end
		end
	end

	def book_tables(table_combination, reservation)
		table_combination.each do |table|
			table.book(reservation)
			table.save
		end
	end

	def rounded_rating
		self.rating.round(1)
	end

	def cost_string
		dollar_signs = ""
		(1..self.cost).each do |i|
			dollar_signs << "$"
		end
		dollar_signs
	end

	private
	def available_tables(time)
		self.tables.order(capacity: :asc).where(booked: false, timeslot: time)
	end
end

app/models/table.rb
class Table < ActiveRecord::Base
	belongs_to :restaurant
	belongs_to :reservation
	has_one :user, through: :reservation

  validates :capacity, presence: true, numericality: {only_integer: true}

	def book(reservation_id)
		self.booked = true
		self.reservation_id = reservation_id
	end

    def unbook()
        self.booked = false
        self.reservation_id = nil
    end
end

app/models/user.rb
class User < ActiveRecord::Base
	has_secure_password

	has_one :owned_restaurant, class_name: 'Restaurant', foreign_key: 'user_id'
	has_many :reservations

  validates :email, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception


  private
  def current_user
  	 if session[:user_id]
      if @current_user.nil?
      	@current_user = User.find(session[:user_id])
      else
      	@current_user = @current_user
      end
    end
  end
  helper_method :current_user

end

app/controllers/reservations_controller.rb
class ReservationsController < ApplicationController

	def index
		@reservations = current_user.reservations
	end

	def show
		@reservation = Reservation.find(params[:id])
	end

	def new
		if current_user
			@reservation = Reservation.new
		else
			redirect_to new_session_path
		end
	end

	def create
		@reservation = Reservation.new(reservation_params)
		@restaurant = Restaurant.find(params[:restaurant_id])
		@party_size = params[:reservation][:party_size].to_i
		@timeslot = DateTime.new(params[:reservation][:year].to_i, params[:reservation][:month].to_i, params[:reservation][:day].to_i, params[:reservation][:hour].to_i)
		if @reservation.save
			@restaurant.book_tables(@restaurant.find_tables_for_party(@party_size, @timeslot), @reservation.id)
			redirect_to user_path(@reservation.user_id)
		else
			render :new
 		end
	end

	def destroy
		@reservation = Reservation.find(params[:id])
		@reservation.tables.each do |table|
			table.unbook
			table.save
		end
		@reservation.destroy
		redirect_to user_path(current_user)
	end

	def edit
		@reservation = Reservation.find(params[:id])
	end

	def update
		@reservation = Reservation.find(params[:id])

		if @reservation.update_attributes(contact_params)
			redirect_to action: :show
		else
			render :edit
		end
	end

	private
	def reservation_params
		params.require(:reservation).permit(:party_size, :user_id, :restaurant_id, :timeslot)
	end
end

app/controllers/restaurants_controller.rb
class RestaurantsController < ApplicationController
  before_action :load_tables, only: [:show]

	def index
  	@restaurants = Restaurant.all
  end

  def show
  	@restaurant = Restaurant.find(params[:id])
  end

  def new
  	@restaurant = Restaurant.new
  end

  def create
  	@restaurant = Restaurant.new(restaurant_params)
  	if @restaurant.save then
  		redirect_to restaurant_path(@restaurant), notice: "#{@restaurant.name} created successfully."
    end
  end

  def edit
  	@restaurant = Restaurant.find(params[:id])
  end

  def update
    @restaurant = Restaurant.find(params[:id])
  	if @restaurant.update_attributes(restaurant_params)
  		redirect_to restaurant_path(@restaurant)
    end
  end

  def destroy
  	@restaurant = Restaurant.find(params[:id])
  	@restaurant.destroy
  	redirect_to user_path, notice: "Restaurant removed successfully!"
  end

  private
  def restaurant_params
  	params.require(:restaurant).permit(:name, :description, :address, :website, :photo, :cost, :rating, :cuisine)
  end

  def load_tables
    @tables = Restaurant.find(params[:id]).tables
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end

  def create
    @user = User.find_by(email: params[:email])
    if @user && @user.authenticate(params[:password])
      session[:user_id] = @user.id
      redirect_to restaurants_url, notice: "Logged in!"
    else
      flash.now[:alert] = "Invalid email or password."
      render :new
    end
  end

  def destroy
    session[:user_id] = nil
    redirect_to restaurants_url, notice: "Logged out!"
  end
end

app/controllers/tables_controller.rb
class TablesController < ApplicationController
  before_action :load_restaurant

  def index
    @tables = @restaurant.tables
  end

  def show
    @table = Table.find(params[:id])
  end

  def new
    @table = Table.new
  end

  def create
    @table = @restaurant.tables.build(table_params)

    if @table.save
      redirect_to restaurant_path(@restaurant), notice: 'Successfully added the desired table(s)'
    else
      flash[:alert] = 'You cannot create a table without a capacity'
      redirect_to restaurant_path(@restaurant)
    end
  end

  def destroy
    @table = Table.find(params[:id])
    @table.destroy
  end

  private
  def table_params
    params.require(:table).permit(:capacity, :timeslot, :booked)
  end

  def load_restaurant
    @restaurant = Restaurant.find(params[:restaurant_id])
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

	def new
		@user = User.new
	end

	def create
		@user = User.new(user_params)
		if @user.save
			session[:user_id] = @user.id
			redirect_to restaurants_path, notice: "Hey, #{@user.first_name}, thanks for signing up!"
		else
			render :action => "new"
		end
	end

	def show
	 	@user = User.find(params[:id])
	end

	def edit
		@user = User.find(params[:id])
	end

	def update
		if @user.update_attributes(user_params)
			redirect_to user_path(@user)
		else
			render :show, alert: "Your profile could not be updated."
		end
	end

	def destroy
		@user = User.find(params[:id])
		@user.destroy
		redirect_to restaurants_url
	end

	private
	def user_params
		params.require(:user).permit(:first_name, :last_name, :email, :password, :password_confirmation)
	end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/reservations_helper.rb
module ReservationsHelper
end

app/helpers/restaurants_helper.rb
module RestaurantsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/tables_helper.rb
module TablesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>

<head>
  <title>SeatYourself</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
  <meta name="viewport" content="width=device-width, initial-scale=1">

  <!-- Font for document -->
<link href='https://fonts.googleapis.com/css?family=Josefin+Sans' rel='stylesheet' type='text/css'>
  <!-- Latest compiled and minified CSS -->
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.5/css/bootstrap.min.css" integrity="sha512-dTfge/zgoMYpP7QbHy4gWMEGsbsdZeCXz7irItjcC3sPUFtf0kuFbDz/ixG7ArTxmDjLXDmezHubeNikyKGVyQ==" crossorigin="anonymous">

<!-- Optional theme -->
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.5/css/bootstrap-theme.min.css" integrity="sha384-aUGj/X2zp5rLCbBxumKTCw2Z50WgIr1vs/PFN4praOTvYXWlVyh2UtNUU0KAUhAX" crossorigin="anonymous">

<!-- Latest compiled and minified JavaScript -->
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.5/js/bootstrap.min.js" integrity="sha512-K1qjQ+NcF2TYO/eI3M6v8EiNYZfA95pQumfvcVrTHtwQVDG+aHRqLi/ETn2uB+1JqwYqVG3LIvdm9lj6imS/pQ==" crossorigin="anonymous"></script>


</head>

<body>
  <div class="header">
    <a style="display:block" href='/restaurants' class="logo">
    <div class="float-left" id="logo"><span class="seat">Seat</span><span id="yourself">Yourself</span><span class="seat">.</span> </div> </a>

  	<% if current_user %>
  		<%= link_to 'Sign Out', session_path(current_user), method: :delete, class: "float-right", id: "signout"%>
  		<%= link_to 'My Profile', user_path(current_user.id), class: "float-right", id: "profile" %>
  	<% else %>
      <%= link_to 'Login', new_session_path, class: "float-right", id: "login" %>
  		<%= link_to 'Sign Up', new_user_path, class: "float-right", id: "signup" %>
  	<% end %>
  </div>

  <div class="main">
    <%= yield %>
  </div>
</body>

</html>

app/views/reservations/new.html.erb
<!-- Available params: :year, :month, :day, :hour, :party_size, :restaurant_id
Make reservation using the params and current_user! -->

<% @restaurant = Restaurant.find(params[:restaurant_id]) %>

<div id="my_profile"> Confirm Your Reservation</div>

    <div class="content_holder">
       
            <p class="res_restaurant"> <%=@restaurant.name%> </p>
            <p class="res_date"> <%="#{params[:day]}/#{params[:month]}/#{params[:year]} at #{params[:hour]}:00."%> </p>
            <p class="res_size"> <%= params[:party_size] %> seats for <%= current_user.first_name %> <%= current_user.last_name %> </p>

            <%= form_for [@restaurant, @reservation] do |f| %>
                <%= f.hidden_field(:user_id, value: current_user.id) %>
                <%= f.hidden_field(:party_size, value: params[:party_size]) %>
                <%= f.hidden_field(:year, value: params[:year]) %>
                <%= f.hidden_field(:month, value: params[:month]) %>
                <%= f.hidden_field(:day, value: params[:day]) %>
                <%= f.hidden_field(:hour, value: params[:hour]) %>
                <%= f.hidden_field(:timeslot, value: DateTime.new(params[:year].to_i, params[:month].to_i, params[:day].to_i, params[:hour].to_i)) %>
                <%= f.hidden_field(:restaurant_id, value: params[:restaurant_id]) %>
                
                <div class="confirm_res">
                    <%= f.submit do %>
                        Confirm Reservation
                    <% end %>
                </div>
            <% end %>
      
    </div>

app/views/reservations/show.html.erb
<h1><%= @user.first_name %></h1>

app/views/restaurants/_form.html.erb
<%= form_for @restaurant do |f| %>

  <% if @restaurant.errors.any? %>

    <p>Failed to create restaurant</p>
    <% @restaurant.errors.full_messages.each do |message| %>
      <%= message %>
    <% end %>
  <% end %>

    <div class="field">
      <%= f.label :name %> <br/>
      <%= f.text_field :name %>
    </div>

    <div class="field">
      <%= f.label :address %> <br/>
      <%= f.text_field :address %>
    </div>

    <div class="field">
      <%= f.label :website %> <br/>
      <%= f.text_field :website %>
    </div>

    <div class="field">
      <%= f.label :cuisine %> <br/>
      <%= f.text_field :cuisine %>
    </div>

    <div class="field">
      <%= f.label :cost, "Cost (1 - 5)" %> <br/>
      <%= f.number_field(:cost, value:3, min:1, max:5) %>
    </div>

    <div class="field">
      <%= f.label :rating, "Rating (0.0 - 5.0)" %> <br/>
      <%= f.number_field(:rating, value:2.5, :step => 0.1, min:0.0, max:5.0) %>
    </div>

    <div class="field">
      <%= f.label :photo, "Photo URL"%> <br/>
      <%= f.text_field :photo %>
    </div>

    <div class="submit">
      <%= submit_tag("Sign Up")%>
    </div>

  <% end %>

app/views/restaurants/edit.html.erb
<div class="form_holder">

<h1 id="signin">Modify your restaurant</h1>

  <%= render 'form' %>

</div>

app/views/restaurants/index.html.erb
<style type="text/css">
   body { background: black !important; } /* Adding !important forces the browser to overwrite the default style applied by Bootstrap */
</style>

<% now = DateTime.now + 1.hours %>

<% if params[:date] == nil %>
    <%date = now%>
  <% else %>
    <%date = DateTime.new(params[:date][:year].to_i,params[:date][:month].to_i,params[:date][:day].to_i,params[:date][:hour].to_i)%>
  <% end %>

<div class="search">
  <%= form_tag("/restaurants", method: "get") do %>
    <%= label_tag(:party_size, "Find a table for ") %>
    <%= select_tag(:party_size, options_for_select([ "1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12" ], "2")) %>
    <%= label_tag(:month, " on ") %>
    <%= select_month(date) %>
    <%= label_tag(:day, "") %>
    <%= select_day(date) %>
    <%= label_tag(:year, "") %>
    <%= select_year(date) %>
    <%= label_tag(:hour, " at ") %>
    <%= select_hour(date, ampm:true) %>
    <%= submit_tag "Search", class: "searchbutton" %>
  <% end %>
</div>

<div class="spacer">
</div>

<% if params[:date] == nil %>
  <% @restaurants.each do |restaurant| %>
      <div class="restaurant_result">
        <div class="photo_container">
          <img id="restaurant_photo" src=<%=restaurant.photo%> />
        </div>
        <div class="info_container">
          <div id="title">
          <% if params[:party_size] == nil %>
            <p id="name"> <%= link_to "#{restaurant.name}", restaurant_path(restaurant.id, :party_size => 2, :date => {year: date.year, month: date.month, day: date.day, hour: date.hour}) %> </p>
          <% else %>
            <p id="name"> <%= link_to "#{restaurant.name}", restaurant_path(restaurant.id, :party_size => params[:party_size], :date => {year: date.year, month: date.month, day: date.day, hour: date.hour}) %> </p>
          <% end %>
          </div>
          <div class="info">
            <p id="address"> <%= restaurant.address %></p>
          </div>
          <div class="info">
            <p id="rating"> <%="#{restaurant.rounded_rating}"%> / 5 </p>
          </div>
          <div class="info">
            <p id="cost"> <%=restaurant.cost_string%> </p>
          </div>
          <div class="info">
            <p id="cuisine"> <%=restaurant.cuisine%> </p>
          </div>
        </div>
      </div>
    <%end%>
<% else %>
  <% @restaurants.each do |restaurant| %>
    <% if restaurant.is_available?(params[:party_size].to_i, date) %>
      <div class="restaurant_result">
        <div class="photo_container">
          <img id="restaurant_photo" src=<%=restaurant.photo%> />
        </div>
        <div class="info_container">
          <div id="title">
          <% if params[:party_size] == nil %>
            <p id="name"> <%= link_to "#{restaurant.name}", restaurant_path(restaurant.id, :party_size => 2, :date => {year: date.year, month: date.month, day: date.day, hour: date.hour}) %> </p>
          <% else %>
            <p id="name"> <%= link_to "#{restaurant.name}", restaurant_path(restaurant.id, :party_size => params[:party_size], :date => {year: date.year, month: date.month, day: date.day, hour: date.hour}) %> </p>
          <% end %>
          </div>
          <div class="info">
            <p id="address"> <%= restaurant.address %></p>
          </div>
          <div class="info">
            <p id="rating"> <%="#{restaurant.rounded_rating}"%> / 5 </p>
          </div>
          <div class="info">
            <p id="cost"> <%=restaurant.cost_string%> </p>
          </div>
          <div class="info">
            <p id="cuisine"> <%=restaurant.cuisine%> </p>
          </div>
        </div>
      </div>
    <%end%>
  <%end%>
<% end %>

app/views/restaurants/new.html.erb
<div class="form_holder">

<h1 id="signin">Add a restaurant</h1>

  <%= render 'form' %>

</div>

app/views/restaurants/show.html.erb
<% date = DateTime.new(params[:date][:year].to_i,params[:date][:month].to_i,params[:date][:day].to_i,params[:date][:hour].to_i) %>

<div class="search">
  <%= form_tag("/restaurants/#{@restaurant.id}", method: "get") do %>
    <%= label_tag(:party_size, "Is there room for ") %>
    <%= select_tag(:party_size, options_for_select([ "1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12" ], params[:party_size])) %>
    <%= label_tag(:month, " on ") %>
    <%= select_month(date) %>
    <%= label_tag(:day, "") %>
    <%= select_day(date) %>
    <%= label_tag(:year, "") %>
    <%= select_year(date) %>
    <%= label_tag(:hour, " at ") %>
    <%= select_hour(date, ampm:true) %>
    ?
    <%= submit_tag "Check", class: "searchbutton" %>
  <% end %>
</div>

<div class="spacer">
</div>

<div class="content">
<h1 id="restaurant_name"><%= @restaurant.name %></h1>
  <% if params[:party_size].to_s.to_i <=  @restaurant.get_current_capacity(date) %>
    <%=link_to "Reserve Now", new_restaurant_reservation_path(@restaurant, :party_size => params[:party_size], :hour => params[:date][:hour], :day => params[:date][:day], :month => params[:date][:month], :year => params[:date][:year]), id: "reservation" %>
  <% else %>
    There isn't enough room for your party at the time above. Try another!
  <% end %>
  <h3>Seats remaining: <%= @restaurant.get_current_capacity(date) %></h3>

<div class="display_photo">
	<img id="photo" src=<%=@restaurant.photo%>>
</div>

<p id="about"> About <%="#{@restaurant.name}"%></p>

<p class="rest_info" id="summary"><%= @restaurant.summary %></p>

<p class="rest_info" id="address"><%= @restaurant.address %></p>

<% if @restaurant.name == "El Caballito Tequila Bar" %>
	<iframe src="https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d2887.0418811522563!2d-79.38918948447603!3d43.64729697912152!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x882b34d19df0e851%3A0xbca9513dc3a259c7!2sEl+Caballito+Tequila+Bar!5e0!3m2!1sen!2sca!4v1448220705057" width="500" height="350" frameborder="0" style="border:0" allowfullscreen></iframe>
<% elsif @restaurant.name == "Artisano Bakery Cafe" %>
	<iframe src="https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d13449.430673290772!2d-79.40006326689036!3d43.65224441286302!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x882b34d19cea5b0b%3A0x258ade270e65fcbb!2sArtisano+Bakery+Cafe!5e0!3m2!1sen!2sca!4v1448221031802" width="500" height="350" frameborder="0" style="border:0" allowfullscreen></iframe>
<% elsif @restaurant.name == "Canoe" %>

	<iframe src="https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d23094.432980247944!2d-79.40006326903307!3d43.65224350648618!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x882b34d2d0792a29%3A0x86a52a26df8b2ee8!2sCanoe!5e0!3m2!1sen!2sca!4v1448221160483" width="500" height="350" frameborder="0" style="border:0" allowfullscreen></iframe>

<% elsif @restaurant.name == "Buca" %>

	<iframe src="https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d2887.1666368496603!2d-79.40267798447621!3d43.64470127912158!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x882b34de58675fb7%3A0xebcebfaa8491dcd9!2sBuca!5e0!3m2!1sen!2sca!4v1448221268151" width="500" height="350" frameborder="0" style="border:0" allowfullscreen></iframe>

<% end %>


<%# Showing this just for display purposes, use the render partial method instead. %>

<a href="<%=@restaurant.website%>" <p class="rest_info" id="website">Visit Website</p></a>

<%= link_to 'Add a table.', new_restaurant_table_path(@restaurant), method:'get' %>

</div>

app/views/tables/_add_tables.html.erb
<p>Add a new table below.</p>

<%= form_for [@table] do |f|%>
  <%= time = DateTime.new(2016,1,1,19) %>

  <div class="field">
      <%= f.label :capacity%> <br/>
      <%= f.number_field(:capacity, value:6, min:1, max:16) %>
  </div>
  <div class="field">
      <%= f.label :timeslot%> <br/>
      <%= f.datetime_field(:timeslot) %>
  </div>
  <div class="submit">
    <%= submit_tag("Create Table")%>
  </div>

<% end %>

app/views/tables/_tables.html.erb
<ul>
<% @tables.each do |table| %>
  <li><%= "#{table.timeslot} : #{table.capacity}" %></li>
<% end %>
</ul>

app/views/tables/create.html.erb
<h1>Tables#create</h1>
<p>Find me in app/views/tables/create.html.erb</p>

app/views/tables/destroy.html.erb
<h1>Tables#destroy</h1>
<p>Find me in app/views/tables/destroy.html.erb</p>

app/views/tables/index.html.erb
<h1>Tables#index</h1>
<p>Find me in app/views/tables/index.html.erb</p>

<%= render partial: 'tables' %>

<%= render partial: 'add_tables' %>

app/views/tables/new.html.erb
<p>Add a new table below.</p>

<%= form_for [@restaurant, @table] do |f|%>
  <% time = DateTime.new(2016,1,1,19) %>

  <div class="field">
      <%= f.label :capacity%> <br/>
      <%= f.number_field(:capacity, value:6, min:1, max:16) %>
  </div>
  <div class="field">
      <%= f.label :timeslot%> <br/>
      <%= f.datetime_select(:timeslot, default: time) %>
  </div>
  <%= f.hidden_field(:booked, value: false) %>
  <div class="submit">
    <%= submit_tag("Create Table")%>
  </div>

<% end %>

app/views/users/create.html.erb
<h1>Create</h1>

app/views/users/new.html.erb
<div class="form_holder">

<h1 id="signin">Make an Account</h1>

	<%= form_for @user do |f| %>

	<% if @user.errors.any? %>
	<div id="alert">
		<p>Failed to create user</p>
		<% @user.errors.full_messages.each do |message| %>
			<p> <%= message %> <p>
		<% end %>
	</div>
	<% end %>

		<div class="field">
			<%= f.label :first_name %> <br/>
			<%= f.text_field :first_name %>
			</div>

		<div class="field">
			<%= f.label :last_name %> <br/>
			<%= f.text_field :last_name %>
		</div>

		<div class="field">
			<%= f.label :email %> <br/>
			<%= f.text_field :email %>
		</div>

		<div class="field">
			<%= f.label :password %> <br/>
			<%= f.password_field :password %>
		</div>

		<div class="field">
			<%= f.label :password_confirmation %> <br/>
			<%= f.password_field :password_confirmation %>
		</div>

		<div class="submit">
			<%= submit_tag("Sign Up")%>
		</div>

	<% end %>
</div>

app/views/users/show.html.erb
<div id="my_profile"> My Profile </div>

<div class="content_holder">

	<p id="first"> <%= "#{@user.first_name}" %> <%= "#{@user.last_name}" %> </p>

	<% if @user.reservations[0] == nil %>
		<p id="myreservations"> No active reservations. </p>
	<% else %>
		<p id="myreservations"> My Reservations: </p>
		<% @user.reservations.each do |reservation| %>
			<div class="reservation">
				<p class="res_restaurant"> <%=Restaurant.find(reservation.restaurant_id).name%> </p>
				<p class="res_size"> <%=reservation.party_size%> Seats </p>
				<p class="res_size"> <%="#{reservation.timeslot.day}/#{reservation.timeslot.month}/#{reservation.timeslot.year} at #{reservation.timeslot.hour}"%>:00</p>

				<div class="button_container">
					<%= link_to restaurant_path(Restaurant.find(reservation.restaurant_id), :date => {:day => reservation.timeslot.day, :month => reservation.timeslot.month, :year => reservation.timeslot.year, :hour => reservation.timeslot.hour}, :party_size => reservation.party_size ) do %>
					<div class="res_button">View Restaurant</div>
					<% end %>

					<%= link_to "Cancel Reservation", user_reservation_path(current_user, reservation), method: :delete, class: "res_button", id: "cancel"  %>

				</div>
			</div>
		<% end %>
	<% end %>

	<p id="membersince"> Member Since: <%= "#{@user.created_at.to_date}" %> </p>

</div>